const express = require("express")
const handlebars = require("express-handlebars")
const productsRouter = require('./routes/api/products.routes.js')
const cartsRouter = require('./routes/api/carts.routes.js')
const messageRouter = require('./routes/api/message.routes.js')
const viewsRouter = require( './routes/views.routes.js')
const messageSocket = require('./utils/messageSocket.js')
const connectDB  = require('./config/index.js')
const { Server, Socket } = require( 'socket.io')

const app = express()
const PORT = process.env.PORT || 8080

const httpServer = app.listen(PORT, error => {
    if(error) console.log(error)
    console.log('Server escuchando en el puerto 8080')
})
const io = new Server(httpServer)
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(express.static(__dirname+'/public'))
app.engine('handlebars', handlebars.engine())
app.set('views', __dirname+'/views')
app.set('view engine', 'handlebars')
connectDB()
app.use(messageSocket(io))
app.use('/api/products', productsRouter)
app.use('/api/carts', cartsRouter)
app.use('/chat', messageRouter)
app.use('/', viewsRouter)
